### PR TITLE
header is responsive

### PR DESCRIPTION
**Pull request by JessBonanno**
## Type of change ##

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Part of a feature.
- [ ] Refactor (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Testing

## Checklist ##

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] added new dependencies
- [ ] added tests
- [ ] updated documentation
- [x] Looks good on large screens
- [x] Looks good on mobile

## Organization ##

- [x] Have you linked this pull request to a Trello card?

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Make workout builder responsive](https://trello.com/c/aqC6dYT5/33-make-workout-builder-responsive)

**Review by jyxsul — APPROVED** [review]
Approved. Looks amazing!

**Review by Alex-Garay — APPROVED** [review]
Have extensively tested locally, looks great!

**Review by nanaboat — APPROVED** [review]
gOOD JOB

**Pull request merged**
