### PR TITLE
Added endpoint to check logged in user

### PR DESCRIPTION
**Pull request by Alex-Garay**
## Description ##

Added endpoint to check logged-in user, responds with the name of the user and a boolean.

## Type of change ##

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Part of a feature.
- [ ] Refactor (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Testing

## Checklist ##

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] added new dependencies
- [ ] added tests
- [ ] updated documentation
- [ ] Looks good on large screens
- [ ] Looks good on mobile

## Organization ##

- [ ] Have you linked this pull request to a Trello card?

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Review by thereactgirl — CHANGES_REQUESTED** [review]
I am seeing an error in the console that says "Cannot set headers after they are sent to the client" but I still get a response. Can you look into this?

**Comment by Alex-Garay** [comment]
> I am seeing an error in the console that says "Cannot set headers after they are sent to the client" but I still get a response. Can you look into this?

Looking into it now

**Review by JessBonanno — APPROVED** [review]
Tested locally and working.
I'm getting an error in the console although the enpoint is working..

"GET /getLoggedInUser 401 5.114 ms - 75
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client"

**Review by thereactgirl — APPROVED** [review]
Great work!

**Pull request merged**
