### PR TITLE
Dashboard setup

### PR DESCRIPTION
**Pull request by thereactgirl**
## Description ##

Initial layout and styles of Dashboard route to see this is /dashboard

## Type of change ##

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Part of a feature.
- [ ] Refactor (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Testing

## Checklist ##

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] added new dependencies
- [ ] added tests
- [ ] updated documentation
- [x] Looks good on large screens
- [x] Looks good on mobile

## Organization ##

- [ ] Have you linked this pull request to a Trello card?

## Review ##

- [x] Is this a work in progress?
- [ ] Is this ready to be reviewed?
- [ ] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by thereactgirl** [comment]
[As a user I can see workouts in my dashboard (front-end)](https://trello.com/c/N7avUyOt/12-as-a-user-i-can-see-workouts-in-my-dashboard-front-end)

**Review by nanaboat — CHANGES_REQUESTED** [review]
Can you remove the .DS_Store file. Add .DS_Store file to .gitignore file at the project root directory.

**Review by JessBonanno — APPROVED** [review]
This looks really great, nice work!  Pulled locally and everything works well!

**Comment by thereactgirl** [comment]
@nanaboat added file to gitignore!

**Review by nanaboat — APPROVED** [review]
Good work!

**Pull request merged**
