### PR TITLE
Welcome page

### PR DESCRIPTION
**Pull request by Tom-Shibley**
## Description ##

DESCRIBE YOUR PULL REQUEST'S CHANGES.  Added SASS as a dependency so do an npm install after pulling

## Type of change ##

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Part of a feature.
- [ ] Refactor (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Testing

## Checklist ##

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] added new dependencies
- [ ] added tests
- [ ] updated documentation
- [ ] Looks good on large screens
- [ ] Looks good on mobile

## Organization ##

- [x] Have you linked this pull request to a Trello card?

## Review ##

- [ ] Is this a work in progress?
- [ ] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Create the register component](https://trello.com/c/uswyzM6S/16-create-the-register-component)

**Comment by JessBonanno** [comment]
[Create the register / login forms](https://trello.com/c/iAonHRMk/17-create-the-register-login-forms)

**Review by jyxsul — APPROVED** [review]
Approved. No new errors generated on start.

**Review by JasonYeh7 — APPROVED** [review]
Look good at my local!

**Pull request merged**
