### PR TITLE
created header with logout button

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##
header

- Created header with first draft logo ( up for discussion )
- Created logout button
- Fixed capitalization on welcome screen

## Type of change ##

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Part of a feature.
- [ ] Refactor (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Testing

## Checklist ##

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] added new dependencies
- [ ] added tests
- [ ] updated documentation
- [x] Looks good on large screens
- [ ] Looks good on mobile

## Organization ##

- [x] Have you linked this pull request to a Trello card?

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?
header

### CODE REVIEW

**Comment by JessBonanno** [comment]
[crate header with logout button](https://trello.com/c/NWJjNBHL/30-crate-header-with-logout-button)

**Comment by JessBonanno** [comment]
[Capitalize signin login placeholders fix spelling on hero text](https://trello.com/c/ZGaok1bu/29-capitalize-signin-login-placeholders-fix-spelling-on-hero-text)

**Review by thereactgirl — APPROVED** [review]
Nice job on this jess! Really pulls everything together! I love the pic super helpful, I pulled down your branch and there are no new errors or warnings in the console. Super clean code and easy to read as well. 👍 👍  Awesome work!

**Review by jyxsul — APPROVED** [review]
Approved. Looks great! Though the logout button could use some more styling but that can wait till after feature freeze.

**Pull request merged**
